name: docker-build-and-push

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=pabra/awstats
          BRANCH="${GITHUB_REF#refs/heads/}"
          COMMITS="$( git rev-list --count "${BRANCH}" )"

          if [ "${BRANCH}" = 'master' ]; then
            TAGS="${DOCKER_IMAGE}:${BRANCH}-${COMMITS}"
            TAGS="${TAGS},${DOCKER_IMAGE}:edge"
          elif [ "${BRANCH}" = '7.7' ]; then
            TAGS="${DOCKER_IMAGE}:${BRANCH}-${COMMITS}"
            TAGS="${TAGS},${DOCKER_IMAGE}:latest"
          elif [ "${BRANCH}" = 'actions' ]; then
            TAGS="${DOCKER_IMAGE}:${BRANCH}-${COMMITS}"
            TAGS="${TAGS},${DOCKER_IMAGE}:edge"
          else
            TAGS=''
          fi
          echo ::set-output name=tags::${TAGS}

      - name: debug tags
        run: |
          set -ex
          echo "TAGS: '${{ steps.prep.outputs.tags }}'"
          git branch --show-current
          git rev-list --count actions
          # git rev-list --count $( git branch --show-current ) ^master
          git rev-list --count $( git branch --show-current )

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: debug cache
        run: |
          set -ex
          ls -lahF /tmp/.buildx-cache

      - name: docker images before
        run: docker image ls

      - name: Build awstats for testing
        uses: docker/build-push-action@v2
        with:
          # outputs: type=docker
          load: true
          tags: pabra/awstats:test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build awstats-test
        uses: docker/build-push-action@v2
        with:
          context: ./test
          file: ./test/Dockerfile
          # outputs: type=docker
          load: true
          tags: pabra/awstats-test:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: docker images after
        run: docker image ls

      - name: run tests
        run: ./run_tests.sh skip_build

      - name: echo running containers 1
        run: docker ps -a

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && steps.prep.outputs.tags != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: github.event_name != 'pull_request' && steps.prep.outputs.tags != ''
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
